repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/aio-libs/sort-all
    rev: v1.2.0
    hooks:
      - id: sort-all
