# Project information
site_name: yatta
site_url: https://gh.seria.moe/yatta
site_author: Seria Ati
site_description: An async API wrapper for Project Yatta (sr.yatta.moe) written in Python.

# Repository
repo_name: seriaati/yatta
repo_url: https://github.com/seriaati/yatta

# Copyright
copyright: Copyright &copy; 2025 - 2025 Seria Ati

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: deep purple
      accent: deep purple

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: deep purple
      accent: deep purple

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["yatta"]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          options:
            backlinks: tree
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            parameter_headings: true
            relative_crossrefs: true
            scoped_crossrefs: true
            type_parameter_headings: true
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_if_no_docstring: true
            show_source: false
            show_bases: false
            separate_signature: true
            signature_crossrefs: true
            show_symbol_type_toc: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            summary: true
            filters:
              - "!^_"
            unwrap_annotated: true
            extensions:
              - griffe_pydantic:
                  schema: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: README.md
  - Getting Started: getting_started.md
  - API Reference:
      - Client: client.md
      - Models: models.md
      - Exceptions: exceptions.md
      - Enums: enums.md
      - Utils: utils.md
