name: Seria's CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # every Monday at 00:00
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Create release
        uses: seriaati/create-release@main
        
  update-deps:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update dependencies & pre-commits
        uses: seriaati/update-deps@main